---
title: "GlobaPlasticWaste"
author: "Alyssa Vanderbeek"
date: "5/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(countrycode)
library(ggplot2)
library(ggalt)
library(ggthemes)
library(ggpubr)
library(gridExtra)
```

```{r}
coast_vs_waste <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/coastal-population-vs-mismanaged-plastic.csv") %>%
  janitor::clean_names() %>%
  filter(year == 2010)

mismanaged_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv") %>%
  purrr::set_names(c("entity", "code", "year", "mismanaged_waste_percap", "gdp_per_capita", "total_pop")) %>%
  filter(year == 2010) %>%
  dplyr::select(entity, mismanaged_waste_percap, gdp_per_capita)

waste_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-plastic-waste-vs-gdp-per-capita.csv") %>%
  purrr::set_names(c("entity", "code", "year", "per_capita_plastic", "gdp_per_capita", "total_pop")) %>%
  filter(year == 2010) %>%
  dplyr::select(entity, per_capita_plastic)

codes <- codelist %>%
  select(iso3c, country.name.en, region, continent) %>%
  janitor::clean_names() %>%
  filter(!is.na(continent)) %>%
  filter(!is.na(region)) %>%
  left_join(CoordinateCleaner::countryref %>% 
              select(iso3, capital.lon, capital.lat), by = c("iso3c" = "iso3")) %>%
  distinct() %>%
  filter(!is.na(capital.lon)) %>%
  filter(!is.na(capital.lat))

waste <- coast_vs_waste %>%
  left_join(mismanaged_vs_gdp, by = "entity") %>%
  left_join(waste_vs_gdp, by = "entity") %>%
  left_join(codes %>%
              dplyr::select(country_name_en, capital.lon, capital.lat), by = c("entity" = "country_name_en")) %>%
  mutate(entity = recode(entity,
                         "United Kingdom" = "UK",
                         "United States" = "USA",
                         "Trinidad & Tobago" = "Trinidad",
                         "Cote d'Ivoire" = "Ivory Coast",
                         "Democratic Republic of Congo" = "Democratic Republic of the Congo",
                         "Congo" = "Republic of Congo",
                         "Hong Kong" = "China",
                         "British Virgin Islands" = "Virgin Islands",
                         "Saint Vincent and the Grenadines" = "Saint Vincent"))
```


```{r}
world <- ggplot2::map_data("world") %>%
  filter(region != "Antarctica") %>%
  left_join(waste, by = c("region" = "entity"))

# China is the leading contributer of mismanaged waste
china = world %>%
  filter(region == "China") %>%
  slice(1) %>%
  mutate(label = "1st in total mismanaged waste\n1st in population")

world %>%
  mutate(percap_waste_cat = cut(mismanaged_waste_percap,breaks = c(0, 0.01, 0.025, 0.05, 0.10, 0.30))) %>% # create categorical variable that breaks down the mismanaged waste per cap into discrete intervals
  ggplot() + 
  geom_cartogram(
    map = world,
    aes(x = long, y = lat, map_id = region, fill = percap_waste_cat),
    color = "black", size = 0.125, alpha = 0.8
  ) +
  viridis::scale_fill_viridis(discrete = T)  +
  labs(
    x = NULL, y = NULL,
    title = "Mismanaged waste per capita (kg/day) in 2010",
    subtitle = "",
    caption = "Source: Our World in Data \n@VanderbeekAM ",
    fill = ""
    ) +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5, size = 15)) +
  theme(plot.subtitle = element_text(hjust = 0.5)) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(nrow = 1)) +
  geom_text(data = china, 
            aes(x = capital.lon, y = capital.lat, label = "China"), 
            nudge_x = -15, nudge_y = -5) + 
  geom_label(data = china, 
             aes(x = capital.lon, y = capital.lat, label = label), 
             size = 2.5, nudge_x = 31, nudge_y = -19) +
  annotate("segment", x = 130, xend = 115, y = 25, yend = 30, colour = "black", size = 1)

ggsave("mismanaged_waste.png", width = 14, height = 8)


## create custom legend using geom_bar
# countries = world %>%
#   group_by(region) %>%
#   slice(1) %>% 
#   mutate(percap_waste_cat = cut(mismanaged_waste_percap,
#                                 breaks = c(0, 0.01, 0.025, 0.05, 0.10, 0.30)),
#          percap_waste_cat_rev = forcats::fct_rev(percap_waste_cat))
# 
# waste_cat_count = countries %>%
#   group_by(percap_waste_cat_rev) %>%
#   summarise(freq = length(percap_waste_cat_rev))
# 
# waste_cat_count %>%
#   ggplot(aes(x = 1, y = freq, fill = percap_waste_cat_rev)) +
#   geom_bar(stat = "identity", width = 0.04, color = "black", size = 0.2) + 
#   viridis::scale_fill_viridis(direction = -1, discrete = T) +
#   scale_x_continuous(limits = c(0.5, 1.5)) +
#   #coord_flip() + 
#   #theme_void() + 
#   theme(legend.position = "none") +
#   geom_text(aes(label = rev(freq)), 
#             position = position_stack(vjust = 0.5)
#             #position = position_dodge(width = 0.1) 
#             #nudge_x = -0.05
# )
# 
# countries %>%
#   left_join(waste_cat_count, by = "percap_waste_cat") %>%
#   ggplot(aes(x = 1, y = percap_waste_cat_rev, fill = percap_waste_cat)) +
#   geom_bar(stat = "identity", width = 0.05) + 
#   viridis::scale_fill_viridis(discrete = T) +
#   scale_x_continuous(limits = c(0.5, 1.5)) +
#   coord_flip() + 
#   theme_void() + 
#   theme(legend.position = "none") +
#   geom_text(aes(label = unique(percap_waste_cat)), vjust=-1)
# 
# data.frame(breaks = c(rep("0", 4),
#                       rep("0.01", 5),
#                       rep("0.025", 6),
#                       rep("0.05", 10),
#                       rep("0.10", 20),
#                       rep("0.30", 60))) %>% # create categorical variable that breaks down the mismanaged waste per cap into discrete intervals
#   ggplot(aes(x = 1, y = breaks, fill = breaks)) +
#   geom_bar(stat = "identity", width = 0.05) + 
#   #theme_void() + 
#   viridis::scale_fill_viridis(discrete = T) +
#   scale_x_continuous(limits = c(0.5, 1.5))

```

```{r}
ggplot(world, aes(x = mismanaged_waste_percap, y = gdp_per_capita)) +
  geom_point() +
  geom_smooth()
```

